### ISSUE TITLE
[Proposal] Async itteration with external service

### ISSUE THREAD

**Issue by OlzhabaevSh** [eymenefealtun/LexiExtract#1]
Hey, thank you for your work. 

I believe your lib can be really useful for a lot of people who would like to get benifits of using [all-words-in-all-languages](https://github.com/eymenefealtun/all-words-in-all-languages).

Looks like [Helpers.ExtractArray](https://github.com/eymenefealtun/LexiExtract/blob/master/LexiExtract/Helpers.cs) works synchronously and it can be bad if someone would like to use your library in his backend app. 

More information why it could be a problem you can read [here]()

## Proposal

```c#

// class name Helpers.
// namespace LexiExtract
// path: LexiExtract/LexiExtract/Helper.cs

internal static Task<string[]> ExtractArrayAsync(string url) 
{
   var httpClient = new HttpClient();

   var response = await httpClient.GetAsync("https://www.google.com");
   var content = await response.Content.ReadAsStringAsync();
   return content.Split(',');
}

```

If you decide to use this approach, please don't forget:
1. maybe it will be better to inject an instance of HttpClient instead of creating it in the method. 
2.  `LexiExtractor.GetLanguageArray` and should also return Task<T>.

**Comment by eymenefealtun** [comment]
Thank you for this nice recommendation. I am going to add  async methods of the existing ones.
